# =============================================================================
# Cloud Build 自動デプロイ設定（mobile-api → Cloud Run）
# =============================================================================
#
# 目的:
#   mainブランチへのマージ時に自動でmobile-apiをCloud Runにデプロイ
#
# トリガー設定:
#   - 名前: mobile-api-auto-deploy
#   - イベント: Push to a branch
#   - ブランチ: ^main$
#   - ファイルフィルタ: mobile-api/**, lib/**, chatwork-webhook/handlers/**, chatwork-webhook/lib/**
#   - 構成ファイル: cloudbuild-mobile-api.yaml
#
# v1.0.0: 初版作成（Phase 6 Mobile API）
# =============================================================================

substitutions:
  _REGION: asia-northeast1
  _SERVICE: soulkun-mobile-api
  _REPO: cloud-run

steps:
  # =============================================================================
  # Step 1: Docker イメージをビルド & Artifact Registry にプッシュ
  # =============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args:
      - 'build'
      - '-f'
      - 'mobile-api/Dockerfile'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}'
    waitFor: ['docker-build']

  # =============================================================================
  # Step 2: Cloud Run にデプロイ
  # =============================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=300s'
      - '--no-allow-unauthenticated'
      - '--min-instances=0'
      - '--max-instances=5'
      - '--update-env-vars=ENVIRONMENT=production'
    waitFor: ['docker-push']

  # =============================================================================
  # Step 3: トラフィックルーティング確認
  # =============================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'traffic-check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -eo pipefail
        echo "🔍 トラフィックルーティング確認..."

        LATEST_REV=$(gcloud run revisions list --service="${_SERVICE}" --region="${_REGION}" \
            --sort-by='~creationTimestamp' --limit=1 --format='value(name)' 2>/dev/null || true)
        TRAFFIC_REV=$(gcloud run services describe "${_SERVICE}" --region="${_REGION}" \
            --format='value(status.traffic[0].revisionName)' 2>/dev/null || true)

        if [ -n "$LATEST_REV" ] && [ -n "$TRAFFIC_REV" ]; then
          if [ "$LATEST_REV" = "$TRAFFIC_REV" ]; then
            echo "✅ トラフィック: ${LATEST_REV} (100%)"
          else
            echo "⚠️ トラフィックが旧リビジョン: ${TRAFFIC_REV}"
            echo "→ 最新リビジョン ${LATEST_REV} に切り替え中..."
            gcloud run services update-traffic "${_SERVICE}" --region="${_REGION}" \
                --to-revisions="${LATEST_REV}=100" 2>&1
            echo "✅ トラフィック切り替え完了: ${LATEST_REV} (100%)"
          fi
        else
          echo "⚠️ リビジョン情報の取得に失敗。手動で確認してください"
        fi
    waitFor: ['deploy-cloud-run']

  # =============================================================================
  # Step 4: デプロイ完了通知
  # =============================================================================
  - name: 'gcr.io/cloud-builders/curl'
    id: 'notify'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "✅ mobile-api Cloud Run デプロイ完了"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "コミット: $COMMIT_SHA"
        echo "ブランチ: $BRANCH_NAME"
        echo "イメージ: ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA"
        echo ""
    waitFor: ['traffic-check']

timeout: '600s'

options:
  logging: CLOUD_LOGGING_ONLY
