# =============================================================================
# Cloud Build 自動デプロイ設定
# =============================================================================
#
# 目的:
#   mainブランチへのマージ時に自動でchatwork-webhookをデプロイ
#   ※テストが失敗したらデプロイしない
#
# トリガー設定（GCPコンソールで設定が必要）:
#   - イベント: Push to a branch
#   - ブランチ: ^main$
#   - ファイルフィルタ: chatwork-webhook/**, lib/**, cloudbuild.yaml
#
# v10.53.0: 初版作成（大規模修繕対応）
# v10.54.3: テスト実行・mypy追加（デプロイ前に品質チェック）
# v10.71.0: deploy.sh と整合（sync_lib.sh, SQL検証, gcloud functions deploy）
# =============================================================================

steps:
  # =============================================================================
  # Step 1: lib/ 同期チェック + Import smoke test
  # =============================================================================
  - name: 'python:3.11-slim'
    id: 'sync-check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -eo pipefail
        echo "🔍 lib/ 同期チェック..."

        # rsync をインストール（sync_lib.sh が必要とする）
        apt-get update -qq && apt-get install -y -qq rsync > /dev/null 2>&1

        # sync_lib.sh --check で完全なミラーチェック
        if ! ./scripts/sync_lib.sh --check; then
          echo ""
          echo "❌ lib/ が同期されていません！"
          echo "修正方法: ./scripts/sync_lib.sh を実行してください。"
          exit 1
        fi

        echo ""
        echo "🔍 Import smoke test..."
        if ! python3 -c "import sys; sys.path.insert(0, 'chatwork-webhook'); import lib" 2>&1; then
          echo "❌ chatwork-webhook/lib/ のインポートに失敗"
          exit 1
        fi
        echo "✅ Import smoke test passed"

  # =============================================================================
  # Step 2: SQLカラム検証（db_schema.json と照合）
  # =============================================================================
  - name: 'python:3.11-slim'
    id: 'sql-validation'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -eo pipefail
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "🔍 SQLカラム検証"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

        if [ ! -f db_schema.json ]; then
          echo "⚠️ db_schema.json が存在しません。SQL検証をスキップします。"
          exit 0
        fi

        ./scripts/validate_sql_columns.sh --all
        echo "✅ SQLカラム検証 PASS"
    waitFor: ['sync-check']

  # =============================================================================
  # Step 3: Python環境セットアップ + テスト実行
  # =============================================================================
  - name: 'python:3.11-slim'
    id: 'run-tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -eo pipefail
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "🧪 テスト実行（失敗したらデプロイ中止）"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

        # 依存関係インストール
        pip install --quiet pytest pytest-asyncio
        pip install --quiet -r chatwork-webhook/requirements.txt 2>/dev/null || true

        # 重要なテストのみ実行（高速化のため）
        echo ""
        echo "📋 重要機能テスト実行..."
        cd /workspace
        python -m pytest tests/test_critical_functions.py tests/test_brain_type_safety.py -v --tb=short

        echo ""
        echo "✅ テスト成功"
    waitFor: ['sql-validation']

  # =============================================================================
  # Step 3.5: 結合テスト（Docker PostgreSQL）
  # =============================================================================
  # 3者合意(Claude + Codex + Gemini): CIで本物のDBに接続するテストが必須
  - name: 'docker'
    id: 'integration-tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -eo pipefail
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "🔗 結合テスト（本物のPostgreSQL使用）"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

        # PostgreSQLコンテナ起動
        docker run -d --name test-postgres \
          -e POSTGRES_USER=test_user \
          -e POSTGRES_PASSWORD=test_pass \
          -e POSTGRES_DB=test_db \
          -p 15432:5432 \
          postgres:15-alpine

        # 起動待ち（最大30秒）
        echo "  PostgreSQL起動待ち..."
        for i in $(seq 1 30); do
          if docker exec test-postgres pg_isready -U test_user -d test_db >/dev/null 2>&1; then
            echo "  PostgreSQL起動完了（${i}秒）"
            break
          fi
          sleep 1
        done

        # 結合テスト実行
        cd /workspace
        pip install --quiet pytest sqlalchemy pg8000
        TEST_DATABASE_URL="postgresql+pg8000://test_user:test_pass@localhost:15432/test_db" \
          python -m pytest tests/integration/ -v --tb=short

        # クリーンアップ
        docker stop test-postgres && docker rm test-postgres

        echo ""
        echo "✅ 結合テスト成功"
    waitFor: ['run-tests']

  # =============================================================================
  # Step 4: 静的型チェック（mypy）
  # =============================================================================
  - name: 'python:3.11-slim'
    id: 'mypy-check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -eo pipefail
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "🔍 静的型チェック（存在しない関数の検出など）"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

        pip install --quiet mypy

        echo ""
        echo "📋 lib/brain/ の型チェック..."
        python -m mypy chatwork-webhook/lib/brain/models.py \
                       chatwork-webhook/lib/brain/core.py \
                       chatwork-webhook/lib/brain/handler_wrappers.py \
                       --ignore-missing-imports \
                       --no-error-summary 2>&1 | head -50

        # mypyはエラーがあっても警告レベルなので、今はデプロイを止めない
        echo ""
        echo "✅ 型チェック完了（警告は記録のみ）"
    waitFor: ['run-tests']

  # =============================================================================
  # Step 5: chatwork-webhook をデプロイ
  # =============================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-chatwork-webhook'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'chatwork-webhook'
      - '--source=chatwork-webhook'
      - '--runtime=python311'
      - '--trigger-http'
      - '--region=asia-northeast1'
      - '--memory=1024MB'
      - '--cpu=1'
      - '--timeout=540s'
      - '--allow-unauthenticated'
      - '--update-env-vars=USE_BRAIN_ARCHITECTURE=true,LOG_EXECUTION_ID=true,ENABLE_MEETING_TRANSCRIPTION=true,ENABLE_MEETING_MINUTES=true,MEETING_GCS_BUCKET=soulkun-meeting-recordings'
    waitFor: ['mypy-check', 'integration-tests']

  # =============================================================================
  # Step 6: トラフィックルーティング確認
  # =============================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'traffic-check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -eo pipefail
        echo "🔍 トラフィックルーティング確認..."

        FUNC_NAME="chatwork-webhook"
        REGION="asia-northeast1"

        LATEST_REV=$(gcloud run revisions list --service="$FUNC_NAME" --region="$REGION" \
            --sort-by='~creationTimestamp' --limit=1 --format='value(name)' 2>/dev/null || true)
        TRAFFIC_REV=$(gcloud run services describe "$FUNC_NAME" --region="$REGION" \
            --format='value(status.traffic[0].revisionName)' 2>/dev/null || true)

        if [ -n "$LATEST_REV" ] && [ -n "$TRAFFIC_REV" ]; then
          if [ "$LATEST_REV" = "$TRAFFIC_REV" ]; then
            echo "✅ トラフィック: ${LATEST_REV} (100%)"
          else
            echo "⚠️ トラフィックが旧リビジョン: ${TRAFFIC_REV}"
            echo "→ 最新リビジョン ${LATEST_REV} に切り替え中..."
            gcloud run services update-traffic "$FUNC_NAME" --region="$REGION" \
                --to-revisions="${LATEST_REV}=100" 2>&1
            echo "✅ トラフィック切り替え完了: ${LATEST_REV} (100%)"
          fi
        else
          echo "⚠️ リビジョン情報の取得に失敗。手動で確認してください"
        fi
    waitFor: ['deploy-chatwork-webhook']

  # =============================================================================
  # Step 7: デプロイ完了通知
  # =============================================================================
  - name: 'gcr.io/cloud-builders/curl'
    id: 'notify'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "✅ chatwork-webhook デプロイ完了"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "コミット: $COMMIT_SHA"
        echo "ブランチ: $BRANCH_NAME"
        echo ""
        echo "品質チェック:"
        echo "  ✅ lib/ 同期チェック（sync_lib.sh --check）"
        echo "  ✅ Import smoke test"
        echo "  ✅ SQLカラム検証"
        echo "  ✅ テスト実行"
        echo "  ✅ 静的型チェック"
        echo "  ✅ トラフィックルーティング確認"
        echo ""
    waitFor: ['traffic-check']

# タイムアウト設定（15分 - テスト時間を考慮）
timeout: '900s'

# ログ設定
options:
  logging: CLOUD_LOGGING_ONLY
