# =============================================================================
# Cloud Build 自動デプロイ設定（proactive-monitor）
# =============================================================================
#
# 目的:
#   mainブランチへのマージ時に自動でproactive-monitorをデプロイ
#
# トリガー設定（GCPコンソールで設定が必要）:
#   - 名前: proactive-monitor-auto-deploy
#   - イベント: Push to a branch
#   - ブランチ: ^main$
#   - ファイルフィルタ: proactive-monitor/**, lib/**, cloudbuild-proactive-monitor.yaml
#   - 構成ファイル: cloudbuild-proactive-monitor.yaml
#
# v10.53.0: 初版作成（大規模修繕対応）
# v10.71.0: deploy.sh と整合（sync_lib.sh, SQL検証, traffic routing）
# =============================================================================

steps:
  # =============================================================================
  # Step 1: lib/ 同期チェック + Import smoke test
  # =============================================================================
  - name: 'python:3.11-slim'
    id: 'sync-check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -eo pipefail
        echo "🔍 lib/ 同期チェック (proactive-monitor)..."

        # rsync をインストール（sync_lib.sh が必要とする）
        apt-get update -qq && apt-get install -y -qq rsync > /dev/null 2>&1

        # sync_lib.sh --check で完全なミラーチェック
        if ! ./scripts/sync_lib.sh --check; then
          echo ""
          echo "❌ lib/ が同期されていません！"
          echo "修正方法: ./scripts/sync_lib.sh を実行してください。"
          exit 1
        fi

        echo ""
        echo "🔍 Import smoke test..."
        if ! python3 -c "import sys; sys.path.insert(0, 'proactive-monitor'); import lib" 2>&1; then
          echo "❌ proactive-monitor/lib/ のインポートに失敗"
          exit 1
        fi
        echo "✅ Import smoke test passed"

  # =============================================================================
  # Step 2: SQLカラム検証（db_schema.json と照合）
  # =============================================================================
  - name: 'python:3.11-slim'
    id: 'sql-validation'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -eo pipefail
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "🔍 SQLカラム検証"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

        if [ ! -f db_schema.json ]; then
          echo "⚠️ db_schema.json が存在しません。SQL検証をスキップします。"
          exit 0
        fi

        ./scripts/validate_sql_columns.sh --all
        echo "✅ SQLカラム検証 PASS"
    waitFor: ['sync-check']

  # =============================================================================
  # Step 3: proactive-monitor をデプロイ
  # =============================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-proactive-monitor'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'proactive-monitor'
      - '--source=proactive-monitor'
      - '--runtime=python311'
      - '--trigger-http'
      - '--region=asia-northeast1'
      - '--memory=512MB'
      - '--timeout=540s'
      - '--no-allow-unauthenticated'
      - '--update-env-vars=USE_BRAIN_ARCHITECTURE=true,LOG_EXECUTION_ID=true'
    waitFor: ['sql-validation']

  # =============================================================================
  # Step 4: トラフィックルーティング確認
  # =============================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'traffic-check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -eo pipefail
        echo "🔍 トラフィックルーティング確認..."

        FUNC_NAME="proactive-monitor"
        REGION="asia-northeast1"

        LATEST_REV=$(gcloud run revisions list --service="$FUNC_NAME" --region="$REGION" \
            --sort-by='~creationTimestamp' --limit=1 --format='value(name)' 2>/dev/null || true)
        TRAFFIC_REV=$(gcloud run services describe "$FUNC_NAME" --region="$REGION" \
            --format='value(status.traffic[0].revisionName)' 2>/dev/null || true)

        if [ -n "$LATEST_REV" ] && [ -n "$TRAFFIC_REV" ]; then
          if [ "$LATEST_REV" = "$TRAFFIC_REV" ]; then
            echo "✅ トラフィック: ${LATEST_REV} (100%)"
          else
            echo "⚠️ トラフィックが旧リビジョン: ${TRAFFIC_REV}"
            echo "→ 最新リビジョン ${LATEST_REV} に切り替え中..."
            gcloud run services update-traffic "$FUNC_NAME" --region="$REGION" \
                --to-revisions="${LATEST_REV}=100" 2>&1
            echo "✅ トラフィック切り替え完了: ${LATEST_REV} (100%)"
          fi
        else
          echo "⚠️ リビジョン情報の取得に失敗。手動で確認してください"
        fi
    waitFor: ['deploy-proactive-monitor']

  # =============================================================================
  # Step 5: デプロイ完了通知
  # =============================================================================
  - name: 'gcr.io/cloud-builders/curl'
    id: 'notify'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "✅ proactive-monitor デプロイ完了"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "コミット: $COMMIT_SHA"
        echo "ブランチ: $BRANCH_NAME"
        echo ""
        echo "品質チェック:"
        echo "  ✅ lib/ 同期チェック（sync_lib.sh --check）"
        echo "  ✅ Import smoke test"
        echo "  ✅ SQLカラム検証"
        echo "  ✅ トラフィックルーティング確認"
        echo ""
    waitFor: ['traffic-check']

# タイムアウト設定（10分）
timeout: '600s'

# ログ設定
options:
  logging: CLOUD_LOGGING_ONLY
