# =============================================================================
# Cloud Build 自動デプロイ設定（proactive-monitor → Cloud Run）
# =============================================================================
#
# 目的:
#   mainブランチへのマージ時に自動でproactive-monitorをCloud Runにデプロイ
#
# トリガー設定（GCPコンソールで設定が必要）:
#   - 名前: proactive-monitor-auto-deploy
#   - イベント: Push to a branch
#   - ブランチ: ^main$
#   - ファイルフィルタ: proactive-monitor/**, lib/**, cloudbuild-proactive-monitor.yaml
#   - 構成ファイル: cloudbuild-proactive-monitor.yaml
#
# v10.53.0: 初版作成（大規模修繕対応）
# v10.71.0: deploy.sh と整合（sync_lib.sh, SQL検証, traffic routing）
# v11.0.0: Cloud Run移行（Docker build + Artifact Registry + gcloud run deploy）
#          lib/ 3コピー同期不要化
# =============================================================================

substitutions:
  _REGION: asia-northeast1
  _SERVICE: proactive-monitor
  _REPO: cloud-run

steps:
  # =============================================================================
  # Step 1: SQLカラム検証（db_schema.json と照合）
  # =============================================================================
  - name: 'python:3.11-slim'
    id: 'sql-validation'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -eo pipefail
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "🔍 SQLカラム検証"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

        if [ ! -f db_schema.json ]; then
          echo "⚠️ db_schema.json が存在しません。SQL検証をスキップします。"
          exit 0
        fi

        ./scripts/validate_sql_columns.sh --all
        echo "✅ SQLカラム検証 PASS"

  # =============================================================================
  # Step 2: Docker イメージをビルド & Artifact Registry にプッシュ
  # =============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args:
      - 'build'
      - '-f'
      - 'proactive-monitor/Dockerfile'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:latest'
      - '.'
    waitFor: ['sql-validation']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}'
    waitFor: ['docker-build']

  # =============================================================================
  # Step 3: Cloud Run にデプロイ
  # =============================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--memory=512Mi'
      - '--timeout=540s'
      - '--no-allow-unauthenticated'
      - '--min-instances=0'
      - '--max-instances=5'
      - '--cpu=1'
      - '--update-env-vars=USE_BRAIN_ARCHITECTURE=true,ENVIRONMENT=production,LOG_EXECUTION_ID=true,OPERATIONS_GCS_BUCKET=soulkun-operations'
      - '--update-secrets=TAVILY_API_KEY=TAVILY_API_KEY:latest'
    waitFor: ['docker-push']

  # =============================================================================
  # Step 4: トラフィックルーティング確認
  # =============================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'traffic-check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -eo pipefail
        echo "🔍 トラフィックルーティング確認..."

        LATEST_REV=$(gcloud run revisions list --service="${_SERVICE}" --region="${_REGION}" \
            --sort-by='~creationTimestamp' --limit=1 --format='value(name)' 2>/dev/null || true)
        TRAFFIC_REV=$(gcloud run services describe "${_SERVICE}" --region="${_REGION}" \
            --format='value(status.traffic[0].revisionName)' 2>/dev/null || true)

        if [ -n "$LATEST_REV" ] && [ -n "$TRAFFIC_REV" ]; then
          if [ "$LATEST_REV" = "$TRAFFIC_REV" ]; then
            echo "✅ トラフィック: ${LATEST_REV} (100%)"
          else
            echo "⚠️ トラフィックが旧リビジョン: ${TRAFFIC_REV}"
            echo "→ 最新リビジョン ${LATEST_REV} に切り替え中..."
            gcloud run services update-traffic "${_SERVICE}" --region="${_REGION}" \
                --to-revisions="${LATEST_REV}=100" 2>&1
            echo "✅ トラフィック切り替え完了: ${LATEST_REV} (100%)"
          fi
        else
          echo "⚠️ リビジョン情報の取得に失敗。手動で確認してください"
        fi
    waitFor: ['deploy-cloud-run']

  # =============================================================================
  # Step 5: デプロイ完了通知
  # =============================================================================
  - name: 'gcr.io/cloud-builders/curl'
    id: 'notify'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "✅ proactive-monitor Cloud Run デプロイ完了"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "コミット: $COMMIT_SHA"
        echo "ブランチ: $BRANCH_NAME"
        echo "イメージ: ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA"
        echo ""
        echo "品質チェック:"
        echo "  ✅ SQLカラム検証"
        echo "  ✅ Docker ビルド & プッシュ"
        echo "  ✅ Cloud Run デプロイ"
        echo "  ✅ トラフィックルーティング確認"
        echo ""
    waitFor: ['traffic-check']

# タイムアウト設定（15分 - Docker build時間を考慮）
timeout: '900s'

# ログ設定
options:
  logging: CLOUD_LOGGING_ONLY
